### ISSUE TITLE
Kotlin Android Dependency error fix

### ISSUE THREAD

**Issue by baksoy** [mintware-de/flutter_barcode_reader#1]
Need to add Kotlin plugin in the root level build.gradle

```
dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.1.4-3"   // NEW. Add this line.
}
```

**Comment by mit-mit** [comment]
Yes, that sounds right. For plugins created with the flutter tool and the `--android-language kotlin`, it's added automatically (as the example above, only we default to version 1.1.51):
https://github.com/flutter/flutter/blob/master/packages/flutter_tools/templates/plugin/android-kotlin.tmpl/build.gradle.tmpl

**Comment by mit-mit** [comment]
cc @matthewtsmith

**Comment by NatoBoram** [comment]
There should be a way to configure it automatically, or at least document it somewhere to prevent this error.
```Bash
* What went wrong:
A problem occurred evaluating project ':barcode_scan'.
> Plugin with id 'kotlin-android' not found.
```

**Comment by marica27** [comment]
Got this error

**Comment by dustin-graham** [comment]
I opened a pull request last week to update the kotlin and gradle deps to latest revisions: https://github.com/apptreesoftware/flutter_barcode_reader/pull/33. 

does this help?

**Comment by clarisha** [comment]
I got some erorr 😩

**Comment by ammaratef45** [comment]
I see the PR is merged, does this make is fixed now?

**Comment by devtronic** [comment]
A new version is available.
