### ISSUE TITLE
Can autofocus be set?

### ISSUE THREAD

**Issue by mehdi-kha** [mintware-de/flutter_barcode_reader#10]
Hello!

First of all, thank you for this wonderful Flutter package! I would like to know how I could manage to set the camera's focus mode? Is there a way to activate autofocus somehow?

Thanks in advance!

Mehdi

**Comment by matthewtsmith** [comment]
No not currently. However, this plugin uses barcode libraries on both iOS and Android that allow that. This is something that could be added to the plugin without too much effort. We currently do not have the bandwidth to add this right now but PRs are welcome.

**Comment by mehdi-kha** [comment]
Okay, thank you very much for your answer and responsiveness 👍
