### ISSUE TITLE
Failed to resolve: android.test.runner:1.1.1

### ISSUE THREAD

**Issue by wheel1992** [mintware-de/flutter_barcode_reader#103]
Below is the output after trying to build gradle.

```java
ERROR: Unable to resolve dependency for ':app@developmentDynamicProfile/compileClasspath': Could not resolve project :barcode_scan.
```

Under` android/build.gradle`
```java
...
dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21"
}
...
```

Under `android/app/build.gradle`
```java
...
dependencies {
    ...
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21"
    ...
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
}
...
```

**Comment by hehuapei** [comment]
My program works fine!
Under android/build.gradle
```
classpath 'com.android.tools.build:gradle:3.3.1'
classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.20'
```
Under android/app/build.gradle
```
estImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version'
```

**Comment by wheel1992** [comment]
Yours will work because it is not AndroidX

**Comment by lColinDl** [comment]
The problem is that you replaced a  `:` with a `.`
Use `androidTestImplementation 'androidx.test:runner:1.1.1'` instead.

**Comment by wheel1992** [comment]
@lColinDl thank you!

**Comment by calistus** [comment]
> The problem is that you replaced a `:` with a `.`
> Use `androidTestImplementation 'androidx.test:runner:1.1.1'` instead.

This works for me

**Comment by AnhDTN** [comment]
ERROR: Failed to resolve: com.androidx.support.test.espresso:espresso-core:3.0.2 :( please help me

**Comment by calistus** [comment]
> ERROR: Failed to resolve: com.androidx.support.test.espresso:espresso-core:3.0.2 :( please help me

Go to the app level build.gradle of your Android directory and add the espresso dependency like this
`    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
`

**Comment by AnhDTN** [comment]
> > ERROR: Failed to resolve: com.androidx.support.test.espresso:espresso-core:3.0.2 :( please help me
> 
> Go to the app level build.gradle of your Android directory and add the espresso dependency like this
> ` androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'`

Thank you <3
