### ISSUE TITLE
Barcode Not Scanning on Lower-end phones

### ISSUE THREAD

**Issue by ghost** [mintware-de/flutter_barcode_reader#106]
Hi,

I'm having an issue with scanning barcodes on low-end phones. The scanner opens fine and am not having any build issues, the scanner simply does not pick up the barcode.

On higher end phones everything works perfectly. Is there a minimum requirement for the camera quality? My use-case specifically requires that I cater for low-end phones.

I'm using version 1.0.0 of the plugin.

Thanks in advance for any help.

**Comment by campioncino** [comment]
This is a common problem using Huawei P8 and P8-lite, P9 and P9-lite

**Comment by ghost** [comment]
Hi @campioncino,

Thanks for the feedback. I'm aware of the issue with the Huawei devices you mentioned. However, the problem I'm experiencing occurs on the following devices which I've tested:

Mobicel R1 - https://www.hi-online.co.za/pdp/mobicel-r1-with-protective-cover/_/A-270085AADQ0;jsessionid=lQio8bH_m2Uh6IivP5SScCbhH36x5Z4RZcO2A09R.com03

Nokia 1 - https://www.gsmarena.com/nokia_1-9052.php

It seems the problem that occurs on the phones linked above is different from the problem with the Huawei devices. When testing with a Huawei P9 lite a black screen is displayed (as if the camera is inaccessible) but when testing with the other devices the camera works fine, the barcodes just aren't scanned.

Thanks again for your help.
