### ISSUE TITLE
Add scanner to container

### ISSUE THREAD

**Issue by rodrigowerberich** [mintware-de/flutter_barcode_reader#107]
Hello, 
I would like to know if there is any way to open the scanner insider a container instead of a whole new windows, and if not, if there are any plans on supporting this soon.

**Comment by linguitang** [comment]
+1

**Comment by angel1st** [comment]
Duplicate to #81, no joy with that regards

**Comment by rodrigowerberich** [comment]
I made a little plugin that is able to do it https://github.com/rodrigowerberich/barcode_platform_view, I didn't fork and make a pull request because I don't know if apptreesoftware is interested in that, my plugin usage is pretty different because it's just a platform view. It is still very early but is functional. Only for android now, but soon on ios too.

**Comment by linguitang** [comment]
@rodrigowerberich First of all, thank you for providing this plugin。But after my tests，[https://github.com/rodrigowerberich/barcode_platform_view](https://github.com/rodrigowerberich/barcode_platform_view) scan speed  is not as good as **flutter_barcode_reader**. I don't know why.

**Comment by rodrigowerberich** [comment]
@linguitang yeah... I also noticed that. Probably something to do with the plarform view rendering, I don't know. Still trying to improve it.

**Comment by linguitang** [comment]
@rodrigowerberich  I made a test， update this from 0.5f to 1.0f， scanning speed is very fast。you can try it.
![image](https://user-images.githubusercontent.com/8371546/56600484-5b209680-662b-11e9-9581-25946daf51ab.png)

**Comment by rodrigowerberich** [comment]
@linguitang Thanks for the heads up! I was thinking about playing with that value tomorow. Nice to know it did the trick!
