### ISSUE TITLE
scanned then crash?

### ISSUE THREAD

**Issue by xiebao** [mintware-de/flutter_barcode_reader#109]
D/GraphicBuffer(31550): unregister, handle(0x9df28500) (w:720 h:1440 s:736 f:0x1 u:b00)
D/GraphicBuffer(31550): unregister, handle(0x9df28a40) (w:720 h:1440 s:736 f:0x1 u:b00)
D/GraphicBuffer(31550): unregister, handle(0x9df28e00) (w:720 h:1440 s:736 f:0x1 u:b00)
V/PhoneWindow(31550): DecorView setVisiblity: visibility = 4, Parent = ViewRoot{ac48364 com.sstech.card/com.hukabao.hukabao.MainActivity,ident = 0}, this = DecorView@90c99cd[MainActivity]
I/zygote  (31550): Background concurrent copying GC freed 37767(8MB) AllocSpace objects, 13(452KB) LOS objects, 76% free, 3MB/15MB, paused 9.882ms total 96.680ms
I/zygote  (31550): Background concurrent copying GC freed 14470(929KB) AllocSpace objects, 45(12MB) LOS objects, 75% free, 3MB/15MB, paused 149us total 137.357ms
I/zygote  (31550): Do full code cache collection, code=125KB, data=110KB
I/zygote  (31550): After code cache collection, code=103KB, data=69KB
D/AndroidRuntime(31550): Shutting down VM
I/flutter (31550): 0003006402,6a8d0a59810302f0eb6405dce3aebc1b
E/AndroidRuntime(31550): FATAL EXCEPTION: main
E/AndroidRuntime(31550): Process: com.sstech.card, PID: 31550
E/AndroidRuntime(31550): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=100, result=-1, data=Intent { (has extras) }} to activity {com.sstech.card/com.hukabao.hukabao.MainActivity}: java.lang.NullPointerException
E/AndroidRuntime(31550): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4359)
E/AndroidRuntime(31550): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4403)
E/AndroidRuntime(31550): 	at android.app.ActivityThread.-wrap19(Unknown Source:0)
E/AndroidRuntime(31550): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1694)
E/AndroidRuntime(31550): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(31550): 	at android.os.Looper.loop(Looper.java:171)
E/AndroidRuntime(31550): 	at android.app.ActivityThread.main(ActivityThread.java:6656)
E/AndroidRuntime(31550): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31550): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(31550): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(31550): Caused by: java.lang.NullPointerException
E/AndroidRuntime(31550): 	at java.io.File.<init>(File.java:282)
E/AndroidRuntime(31550): 	at com.hukabao.hukabao.MainActivity.installApk(MainActivity.kt:131)
E/AndroidRuntime(31550): 	at com.hukabao.hukabao.MainActivity.onActivityResult(MainActivity.kt:115)
E/AndroidRuntime(31550): 	at android.app.Activity.dispatchActivityResult(Activity.java:7341)
E/AndroidRuntime(31550): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4355)
E/AndroidRuntime(31550): 	... 9 more
D/Camera-JNI(31550): (tid:31565)[~MtkJNICameraContext] this:0x81fcba60 
I/Process (31550): Sending signal. PID: 31550 SIG: 9
Lost connection to device.

**Comment by xiebao** [comment]
barcode_scan: ^1.0.0

**Comment by abhriyaroy** [comment]
Getting this issue on 3.0.0

**Comment by bradleyhart** [comment]
I am getting this issue on 3.0.1, did you have a work around?
