### ISSUE TITLE
There're always a white screen before scan screen in Android phone

### ISSUE THREAD

**Issue by jintangWang** [mintware-de/flutter_barcode_reader#110]
I use `flutter1.2` and `barcode_scan1.0.0`. It works well in IOS, but there're always a white screen before scan screen in Android phone. I ran app on Huawei P10, Red mi 5A and OnePlus 5, all of them had the problem. As below clipped gif show:
![white screen show](https://user-images.githubusercontent.com/12557847/56862433-641fb800-69dd-11e9-8375-3be96b1ee276.gif)

**Comment by jintangWang** [comment]
Sorry about the dirty keyboard

**Comment by devtronic** [comment]
Does #186 solves your problem?
