### ISSUE TITLE
Package does not exists - android

### ISSUE THREAD

**Issue by aravindhkumar23** [mintware-de/flutter_barcode_reader#112]
Bar code scanner was working fine but now it showing me error

followed the installation instruction from [github](https://github.com/apptreesoftware/flutter_barcode_reader)

```
/Users/aravindhkumar/Projects/test_work/test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:4: error: package com.apptreesoftware.barcodescan does not exist
import com.apptreesoftware.barcodescan.BarcodeScanPlugin;

/Users/aravindhkumar/Projects/test_work/test_app/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:18: error: cannot find symbol
    BarcodeScanPlugin.registerWith(registry.registrarFor("com.apptreesoftware.barcodescan.BarcodeScanPlugin"));
    ^
  symbol:   variable BarcodeScanPlugin
  location: class GeneratedPluginRegistrant
```

**Tested with  barcode_scan: 0.0.8 and barcode_scan: 1.0.0 it shows the above error**

error not showing when using barcode_scan: 0.0.7

can anyone help me with this? I need to deploy the app to play store?

**Comment by devtronic** [comment]
Try `flutter clean`, remove all dependencies and generated files and run `pub install` and `flutter build apk`
