### ISSUE TITLE
Devices with infrared scanner integrated.

### ISSUE THREAD

**Issue by hesos** [mintware-de/flutter_barcode_reader#113]
We've built an app that runs on multiple kinds of devices,  there are some of them with integrated infrared scanner.
On those devices the plugin is unable to open the camera, most likely the scanner is set as the first background camera. 

So my request is to have the chance to set the camera to use or/and  get some variable where we can check if the plugin got the camera connection.

**Comment by devtronic** [comment]
`v3.x` will support camera selection. See also https://github.com/mintware-de/flutter_barcode_reader/pull/185
