### ISSUE TITLE
App is not launched on Android device.

### ISSUE THREAD

**Issue by xcoinmakers-fukuda** [mintware-de/flutter_barcode_reader#114]
I have some issues. Please help...
I tried to use this library.

With iOS device(both emulator and  actual machine), it works.

But with android device(same on ), it doesn't work.
App was built but couldn't be started correctly, just displayed the scan screen directly.
and on the console window, `Waiting for observatory port to be available...` was displayed.

And I have already applied the setting about AndroidX.

I changed files like below.
-  android > build.gradle
```gradle
buildscript {
    ext.kotlin_version = '1.3.20'
    ....

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21"
    }
}
```

- android > app > build.gradle
```gradle
apply plugin: 'kotlin-android'

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.21"
}
```

- android > app > src > main > AndroidManifest.xml
```xml
<uses-permission android:name="android.permission.CAMERA" />

<activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity"/>
```

**Comment by bramburn** [comment]
i had to change the SDK down to 16 to get it work.

**Comment by ChenArno** [comment]
> i had to change the SDK down to 16 to get it work.

flutter sdk?

**Comment by devtronic** [comment]
I can not reproduce the problem in a new flutter project.
