### ISSUE TITLE
variant.getPackageLibrary obsolete

### ISSUE THREAD

**Issue by bramburn** [mintware-de/flutter_barcode_reader#115]
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getPackageLibrary(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.
Affected Modules: barcode_scan

**Comment by ibrahimyu** [comment]
+1
Looks like `apply plugin: 'kotlin-android'` part prevents the app from building.

**Comment by bramburn** [comment]
i had to configure a lot of the gradle and aswell as include javasdks for it to work. The manifest tutorial also did not work. I will probably fork and push some updated comments later this week.

**Comment by qliqdev** [comment]
> i had to configure a lot of the gradle and aswell as include javasdks for it to work. The manifest tutorial also did not work. I will probably fork and push some updated comments later this week.

Hello. does it fixed?

**Comment by devtronic** [comment]
Please update to the latest version and check if the problem was solved.
