### ISSUE TITLE
Incompatibility with background fetch

### ISSUE THREAD

**Issue by mohamedameer020** [mintware-de/flutter_barcode_reader#116]
We cleared the issue in our fork. Please update.

https://github.com/mohamedameer020/flutter_barcode_reader/commit/59cf3623623fadd0e420bd6c92bea58b6de8cf69

**Comment by lukasvalik** [comment]
@mohamedameer020 Thanks, works like a charm

**Comment by devtronic** [comment]
Should be solved in the latest release
