### ISSUE TITLE
Multi barcode scan 

### ISSUE THREAD

**Issue by mohamedameer020** [mintware-de/flutter_barcode_reader#117]
Multiple barcode scan in single activity in android. Added in our fork. Please update.

https://github.com/mohamedameer020/flutter_barcode_reader/commit/9ed240605d534912adfb7cd035437f83a57ae372

**Comment by kenthinson** [comment]
@mohamedameer020 does this let you scan more then one code without the view automatically popping back to the previous screen?

**Comment by bottle-rocket-11** [comment]
@mohamedameer020 how do we use this in the api? Thank you in advance;

**Comment by devtronic** [comment]
Move discussion to https://github.com/mintware-de/flutter_barcode_reader/issues/147
