### ISSUE TITLE
Adding Kotlin to existing Flutter project?

### ISSUE THREAD

**Issue by rgbinnovation** [mintware-de/flutter_barcode_reader#121]
Hi all,

The documentation mentions how to add Kotlin to a new project, but not an existing one? How can I add it to my existing Flutter project? Hope anyone can help.

**Comment by eelishiram** [comment]
@rgbinnovation have you been able to do this?

**Comment by rgbinnovation** [comment]
Yes. You simply have to add a single file in Kotlin format (forgot the name of it) and it will automatically upgrade. Can be an empty file. Add it using android studio. Just google the file type name.
