### ISSUE TITLE
Update example sources and installation docs

### ISSUE THREAD

**Issue by AlexanderArendar** [mintware-de/flutter_barcode_reader#124]
Hi guys,

You have an awesome plugin but it is a bit frustrating to install it for Android when following the steps in your docs or looking at the Example sources.
A lot of people encounter this problem (me too): https://stackoverflow.com/questions/42843441/kotlin-error-could-not-find-org-jetbrains-kotlinkotlin-stdlib-jre71-0-7

It is just to update two characters 'jre' -> 'jdk' which solves the problem. Would be great if you update docs/Example so people have less troubles installing the plugin

Thanks a lot

**Comment by kenthinson** [comment]
same happened to me.
