### ISSUE TITLE
How we fix orientation landscape for bar code scanner  screen

### ISSUE THREAD

**Issue by madhusudhan-sahani** [mintware-de/flutter_barcode_reader#125]
Hi, 
I have tried many things to fix the orientation in the scanner screen.

`SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
    .then((_) {
      runApp(new MyApp());
    });`
And
`SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
    ]);`

my other screen's orientation fixed but the scanner page orientation is not being fixed.

**Comment by devtronic** [comment]
If you want a fixed orientation, you've to this in the AndroidManifest.xml / in Xcode
