### ISSUE TITLE
Changed text is not displayed

### ISSUE THREAD

**Issue by cristianfb1989** [mintware-de/flutter_barcode_reader#130]
Hello, I modified the string in the file but when running the plugin I do not see the modified text. Can you help me?
![0bBF5Y5UIV](https://user-images.githubusercontent.com/16965222/60990079-fa495600-a31d-11e9-9574-0d847d69b831.png)
![plCvc0xLyQ](https://user-images.githubusercontent.com/16965222/60990082-fa495600-a31d-11e9-9f5d-b580177904b9.png)

**Comment by cristianfb1989** [comment]
https://github.com/apptreesoftware/flutter_barcode_reader/pull/54

**Comment by zzb999** [comment]
1. flutter 插件

**Comment by zzb999** [comment]
1. flutter 插件
2. android 插件，flutter MethodChannel 调native，android/ios
