### ISSUE TITLE
Barcode still scanning

### ISSUE THREAD

**Issue by myoganugraha** [mintware-de/flutter_barcode_reader#133]
is theres anyone know how to dispose the barcode scanner after scan was completed ?

my flow is, open a page -> scan function is called on initstate -> after scan complete, the data sent to api

the process on same page

but i check the log, the camera still scanning

**Comment by lookfirst** [comment]
@myoganugraha You don't mention the OS, but on iOS, this fixes it:

https://github.com/apptreesoftware/flutter_barcode_reader/issues/60#issuecomment-511096909

**Comment by devtronic** [comment]
A new version was published to pub.dev.
Update your dependencies and check if the problem was solved.
