### ISSUE TITLE
Error Compiling with barcode_scan: 1.0.0

### ISSUE THREAD

**Issue by richardcarmichael** [mintware-de/flutter_barcode_reader#137]
I get the following error messages when I compile with barcode scanner 1.0.0:

_FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preDebugBuild'.
> Android dependency 'androidx.core:core' has different version for the compile (1.0.0) and runtime (1.0.1) classpath. You should manually set the same version via DependencyResolution_

Works fine with version 0.0.8 but I need the AndroidX support.

**Comment by YeDaxia** [comment]
I meet the same problem. 

I change the kotlin version as the same as this [project](https://github.com/apptreesoftware/flutter_barcode_reader/blob/master/android/build.gradle), the error pass off.

```
ext.kotlin_version = '1.3.20'
```

**Comment by richardcarmichael** [comment]
Thanks YeDaxia - Fixed it by updating and adding the dependencies used in the project

dependencies {
        classpath 'com.android.tools.build:gradle:3.3.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.20"
    }
