### ISSUE TITLE
Scan QRCode Customer View?

### ISSUE THREAD

**Issue by shiyuan17** [mintware-de/flutter_barcode_reader#143]
扫描界面可以自定义不？

**Comment by cornsauce** [comment]
You may try to clone this project and customize it with your own code...

**Comment by wm20111003** [comment]
same problem!  
How to customize Scanner UI?

**Comment by devtronic** [comment]
What exactly do you want to modify?

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
