### ISSUE TITLE
Rotation lock doesn't work

### ISSUE THREAD

**Issue by cristianfb1989** [mintware-de/flutter_barcode_reader#149]
Hello everyone, I tell you to configure the necessary codes to block but even so, to change the position of the cell phone, the camera does the rotation. Can someone help me?

**android\app\src\main\AndroidManifest.xml**
`<activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:screenOrientation="portrait">`

**lib\main.dart**
`void main() {
  SystemChrome.setPreferredOrientations([
    DeviceOrientation.portraitUp,
  ]);
  runApp(MyApp());
}`

**plugins\flutter_barcode_reader-master\android\src\main\AndroidManifest.xml**
`<application>
    <activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity" android:screenOrientation="portrait" />
  </application>
</manifest>
`

plugins\flutter_barcode_reader-master\ **example** \android\app\src\main\AndroidManifest.xml
```
<activity
            android:name="com.apptreesoftware.barcodescanexample.MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            android:screenOrientation="portrait"
            >
```

plugins\flutter_barcode_reader-master\ **example** \lib\main.dart
```
void main() {
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(new MyApp());
}
```
![Screenshot_1568895635](https://user-images.githubusercontent.com/16965222/65244174-4e13b080-dac0-11e9-85b2-5f7a936da781.png)

**Comment by BharatsDruv** [comment]
// wait until `setPreferredOrientations` is done and start the app
// this works.
void main() {
  SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp])
    .then((_) {
      runApp(new MyApp());
    });
}

**Comment by cristianfb1989** [comment]
@BharatsDruv Thank you very much!
