### ISSUE TITLE
Request - Camera outline ratio

### ISSUE THREAD

**Issue by psyanite** [mintware-de/flutter_barcode_reader#152]
Hi, great library thank you so much for creating it!

I have a request. I am using Android and when I open the scanner, I see it's not in a 1x1 aspect ratio, it would be great to customize it such that I can use a 1x1 square instead of a 4x3 square.

Cheers!

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
