### ISSUE TITLE
I cannot compare the barcode value with a String

### ISSUE THREAD

**Issue by HannHank** [mintware-de/flutter_barcode_reader#155]
i cannot compare the value barcode, with a simple String. 

` String barcode = await BarcodeScanner.scan();
       if(barcode == '1'){`
I do not know why, but if I log the qrcode in the Terminal it show "1" so it have to be true, but the code do not go inside, that if statement. 

thanks in advanced

**Comment by irperera** [comment]
what error do you get?

**Comment by HannHank** [comment]
Sorry I forgot to close that issue, the issue was, that the Qrcode had a speace at the End. So in ther Terminal "1" and "1 " looks the same, but it isn't :). So for anyone you have the same Problem with string comparison, checking the length of the String, might be a good idea.
