### ISSUE TITLE
BarcodeScanPlugin.kt: (18, 21): Unresolved reference: MethodChannel

### ISSUE THREAD

**Issue by nanchen2251** [mintware-de/flutter_barcode_reader#157]
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (5, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (6, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (7, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (8, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (9, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (10, 8): Unresolved reference: io
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (12, 50): Unresolved reference: MethodCallHandler
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (13, 5): Unresolved reference: PluginRegistry
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (14, 16): One type argument expected for class Result<out T>
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (17, 33): Unresolved reference: Registrar
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (18, 21): Unresolved reference: MethodChannel
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (25, 3): 'onMethodCall' overrides nothing
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (25, 35): Unresolved reference: MethodCall
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (25, 55): One type argument expected for class Result<out T>
e: /Users/liushilin/.pub-cache/hosted/http%58%47%47dart-pub.byted.org/barcode_scan-1.0.0/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScanPlugin.kt: (39, 3): 'onActivityResult' overrides nothing

**Comment by devtronic** [comment]
What are the steps to reproduce the problem?
