### ISSUE TITLE
How to tweak the look of the scanner?

### ISSUE THREAD

**Issue by ferdiamg** [mintware-de/flutter_barcode_reader#158]
**I've got the following design in React Native that we want to port to Flutter:**
Is it possible to use flutter_barcode_reader like in the attached screenshot? Every example I see theres a big modal/activity being displayed after a typical "Scan"-FloatingActionButton is being tapped. 
Sadly the documentation is extremely sparse regarding the design/look.

**I just want to have small square that is able to scan a QR code..**
![qrscreenRN](https://user-images.githubusercontent.com/19799412/67960017-f22d6300-fbf9-11e9-903a-89fcbeb83127.png)

Is it possible?

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
