### ISSUE TITLE
iPad Pro iPadOS 13.2 the window is clipped

### ISSUE THREAD

**Issue by StephanCassel** [mintware-de/flutter_barcode_reader#159]
Hi

iPad Pro iPadOS 13.2 the window is clipped, see pic. The scanner works but it doesn't looks good

![Screenshot 2019-11-06 at 20 47 52](https://user-images.githubusercontent.com/5372762/68332530-47281800-00d7-11ea-8b8e-ddef0e6af865.png)

**Comment by terry8204** [comment]
Have the same problem, need improve.

**Comment by terry8204** [comment]
- (void)showBarcodeView {
    BarcodeScannerViewController *scannerViewController = [[BarcodeScannerViewController alloc] init];
    UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:scannerViewController];
    scannerViewController.delegate = self;
   **scannerViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    navigationController.modalPresentationStyle = UIModalPresentationFullScreen;**
    [self.hostViewController presentViewController:navigationController animated:NO completion:nil];
}

add two lines in the BarcodeScanPlugin.m
scannerViewController.modalPresentationStyle = UIModalPresentationFullScreen;
    navigationController.modalPresentationStyle = UIModalPresentationFullScreen;

**Comment by StephanCassel** [comment]
Terry
That is a very good finding. I guess **barcode_scan** package will soon be updated.
Thanks to you and to the barcode_scan team.

**Comment by chuanner** [comment]
I have the same situation. The page looks ugly. I hope this problem can be fixed as soon as possible~~

**Comment by Stephan-Enoro** [comment]
Yes, it would be smashing. barcode_scan is an excellent package and we are depending on it. 
Thanks is advanced.

**Comment by mikhail-karan** [comment]
I'm having this issue as well and would love for the pull request that was created to be merged. Thanks!

**Comment by devtronic** [comment]
@StephanCassel: Please pull the master branch and check if the issue is still there. PR #167 contains a fix a similar problem

**Comment by Stephan-Enoro** [comment]
Hi @devtronic  
Sorry about the delay. On journey.
Everything looks very good.
Thanks.
