### ISSUE TITLE
Publish a new version on Pub

### ISSUE THREAD

**Issue by FedericoMatera** [mintware-de/flutter_barcode_reader#166]
Could you please publish an update on Pub?
The current version has some critical problem.
In my case, my app crashes because there isn't this guard in `BarcodeScanPlugin.kt`:
```
if (registrar.activity() != null) {
...
}
```

**Comment by millievn** [comment]
flutter release version 1.12.13 with some great changes.  Maybe a lot of work should to do to fit it.

**Comment by devtronic** [comment]
A new version is available https://pub.dev/packages/barcode_scan
