### ISSUE TITLE
Only Barcode

### ISSUE THREAD

**Issue by alejantab** [mintware-de/flutter_barcode_reader#169]
Hello, How can I specified only barcode feature?, in my App I don't need Scan QR.

**Comment by devtronic** [comment]
This is not yet possible.

**Comment by devtronic** [comment]
This feature will be available in the next major release (3.x) 🙂

**Comment by devtronic** [comment]
Feel free to test: https://github.com/mintware-de/flutter_barcode_reader/pull/185

**Comment by devtronic** [comment]
https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
