### ISSUE TITLE
SDK location not found

### ISSUE THREAD

**Issue by SamukaM** [mintware-de/flutter_barcode_reader#175]
I am having a problem with the application build;
I'm using MacBook in Catalina version;
Here's a picture of the reported issue:

![image](https://user-images.githubusercontent.com/42897100/72636714-6eecf500-393e-11ea-9dc7-ca6cb6b49c54.png)

**Comment by aparra** [comment]
Defining `ANDROID_HOME` has ran smoothly for me.
