### ISSUE TITLE
Android back button without scanning: FormatException (FormatException: Invalid envelope)

### ISSUE THREAD

**Issue by sgehrman** [mintware-de/flutter_barcode_reader#177]
Exception has occurred.
FormatException (FormatException: Invalid envelope)

**Comment by pkcpkc** [comment]
Me got the same problem:
Pressing back button without scanning results in the FormatException: Invalid envelope.

I guess in this case there might be a null value involved when returning from BarcodeScanner.scan()

Interesting enough: The FormatException only occurs in debug mode - running the app without debugger attached this error is not thrown on back button.

**Comment by eric-5512** [comment]
I not look Back Button

**Comment by devtronic** [comment]
In the current dev release the scan() method returns a result object which contains a resulttype.cancelled instead of throwing an exception: https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
