### ISSUE TITLE
Can't get it to work on IOS

### ISSUE THREAD

**Issue by 04fsnape** [mintware-de/flutter_barcode_reader#18]
I've been having trouble getting this to work on IOS (it works fine in Android).

I have added

```
<key>NSCameraUsageDescription</key>
<string>Camera permission is required for barcode scanning.</string>
```

to my info.plist.

I created the flutter project on windows in android studio, then git cloned it on my mac and tried to run the ios folder from there, but whenever I run it I get this error:

> 'barcode_scan/BarcodeScanPlugin.h' file not found

Is this a bug or am I doing something wrong?

Please help, I need this to work quite urgently.

Thanks.

**Comment by juani21** [comment]
upgrade flutter and cocoapod brew...
post you flutter doctor
