### ISSUE TITLE
Looking for someone to take over this plugin

### ISSUE THREAD

**Issue by matthewtsmith** [mintware-de/flutter_barcode_reader#181]
See [README](https://github.com/apptreesoftware/flutter_barcode_reader/blob/master/README.md)

**Comment by devtronic** [comment]
Yep, here 🙂

**Comment by devtronic** [comment]
How can I contact you?

**Comment by matthewtsmith** [comment]
@devtronic Sent you an email.

**Comment by devtronic** [comment]
Transfer complete. Thank you very much for your great work so far, @matthewtsmith!
