### ISSUE TITLE
Option to select default camera (primary/secondary)

### ISSUE THREAD

**Issue by ghost** [mintware-de/flutter_barcode_reader#184]
Now scanner open primary camera as default.
No options are available for change the camera.
Is it possible for ios?

**Comment by devtronic** [comment]
Not yet, sorry. I need to rewrite the platform communication. After that we can pass a configuration object to the scan() method. This change has the highest priority at the moment. Maybe it's done in 1-3 weeks. I'll let you know if there is something new.

**Comment by devtronic** [comment]
It's easier than I thought. This feature will be available in the next major release (3.x) 🙂

**Comment by ghost** [comment]
@devtronic  Thanks for the update. Great work :)

**Comment by devtronic** [comment]
Feel free to test: https://github.com/mintware-de/flutter_barcode_reader/pull/185

**Comment by devtronic** [comment]
https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
