### ISSUE TITLE
IOS: Module 'barcode_scan' not found 

### ISSUE THREAD

**Issue by qzhao1992** [mintware-de/flutter_barcode_reader#191]
![Screen Shot 2020-03-09 at 3 20 46 PM](https://user-images.githubusercontent.com/15388708/76253948-9adb7700-6219-11ea-8dc6-0119de178aab.png)
![Screen Shot 2020-03-09 at 3 20 31 PM](https://user-images.githubusercontent.com/15388708/76253958-a29b1b80-6219-11ea-86d6-64179b067237.png)

**Comment by devtronic** [comment]
Please post the output of `flutter run --verbose`

**Comment by qzhao1992** [comment]
I created a new project and copied all the code into the new project. It's working now
