### ISSUE TITLE
Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61.

### ISSUE THREAD

**Issue by cvanderhaar** [mintware-de/flutter_barcode_reader#193]
Could not resolve org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.61.

**Comment by cvanderhaar** [comment]
Trying to use this i my flutter app but keep getting this error and followed your solution on the git page...what else can it be please

**Comment by devtronic** [comment]
Maybe gradle isn't in sync. Try to open the Android Module directly in Android Studio and built it there. (https://flutter.dev/docs/development/tools/android-studio#android-ide)

**Comment by cvanderhaar** [comment]
Will try that and come back to you

**Comment by cvanderhaar** [comment]
Getting the below error now:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':barcode_scan' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51

**Comment by devtronic** [comment]
The plugin was updated in the current dev release: https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
