### ISSUE TITLE
Issue with add-to-app

### ISSUE THREAD

**Issue by mikhail-karan** [mintware-de/flutter_barcode_reader#195]
Hi,

This is a probably a very niche use case but what I'm doing is adding multiple flutter modules to my already created Cordova iOS application. I am then Launching the modules using flutter Add-to-app and PlatformChannel communication from iOS to flutter. I essentially have one Umbrella module that handles the importing and navigation between all my other flutter modules.

The issue is that when I try to run the .scan() function it gives me this error:

`2020-03-18 15:03:25.713703-0400 WMVC[1706:1430482] Warning: Attempt to present <UINavigationController: 0x1441eb000>  on <CDVViewController: 0x143e09fe0> which is already presenting <FlutterViewController: 0x144979800>`

The barcode scanning works on its own, but when I add it to my iOS app (through the umbrella app) it gives me the above error. 

Thanks and let me know if you need to see any of my code.

**Comment by devtronic** [comment]
Please provide a minimal working example to reproduce the problem.
