### ISSUE TITLE
can we return also type of of the scan if its BR or QR?

### ISSUE THREAD

**Issue by kw2019ltd** [mintware-de/flutter_barcode_reader#200]

**Comment by kw2019ltd** [comment]
hi can we return instead of code (future) to return object which contain the code and type (if its QR or Bar..) and if its barcode to return barcode type (pdf,code128 etc)...

static Future scan({Configuration config}) async =>
await _channel.invokeMethod('scan', config?.writeToBuffer());

**Comment by devtronic** [comment]
https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
