### ISSUE TITLE
App Crash on android device

### ISSUE THREAD

**Issue by MrJohn2014** [mintware-de/flutter_barcode_reader#210]
App doing well on my iOS device, but it crashes on android device when i click the scan button. Error: android.content.ActivityNotFoundException: Unable to find explicit activity class {***/de.mintware.barcode_scan.BarcodeScannerActivity} Any suggestion for that? i use the version barcode_scan 2.0.2

**Comment by devtronic** [comment]
Does the problem also exist in the latest dev version? https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.3


If yes, please provide a minimal working example to reproduce the problem.

**Comment by Bravo2x** [comment]
> App doing well on my iOS device, but it crashes on android device when i click the scan button. Error: android.content.ActivityNotFoundException: Unable to find explicit activity class {***/de.mintware.barcode_scan.BarcodeScannerActivity} Any suggestion for that? i use the version barcode_scan 2.0.2


Hi i faced the same issue (both version crashed 2.0.2 and 3.0.0), if i have next expression in my AndroidManifest.xml   :       tools:node="replace" - once i have deleted it  plugin works fine
