### ISSUE TITLE
Access denied finding property "vendor.camera.aux.packagelist"

### ISSUE THREAD

**Issue by themisir** [mintware-de/flutter_barcode_reader#212]
I'm getting lots of this kind of messages on android studio output when scanner is open.

```
E/libc    (27455): Access denied finding property "vendor.camera.aux.packagelist"
E/libc    (27455): Access denied finding property "vendor.camera.aux.packagelist2"
```

It doesn't breaks something but I wanna know that is the issue on project side or package side?

![image](https://user-images.githubusercontent.com/29130291/79567804-e52bff80-80c5-11ea-802c-e5205d401764.png)

## `pubspec.yaml`

```yaml
dependencies:
  # A flutter plugin for scanning 2D barcodes and QRCodes via camera.
  barcode_scan: ^2.0.2
```

## `flutter doctor`

```
[√] Flutter (Channel master, v1.16.4-pre.80, on Microsoft Windows [Version 10.0.18363.778], locale en-US)
    • Flutter version 1.16.4-pre.80 at D:\flutter
    • Framework revision 77ea848c46 (2 weeks ago), 2020-04-02 10:57:37 -0700
    • Engine revision 46277fd2ca
    • Dart version 2.8.0 (build 2.8.0-dev.18.0 b177e44ffa)


[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\<redacted>\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 28.0.3
    • ANDROID_HOME = C:\Users\<redacted>\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[!] Visual Studio - develop for Windows (Visual Studio Community 2019 16.5.3)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.5.30002.166
    X Visual Studio is missing necessary components. Please re-run the Visual Studio installer for the
      "Desktop development with C++" workload, and include these components:
        MSBuild
        MSVC v142 - VS 2019 C++ x64/x86 build tools
         - If there are multiple build tool versions available, install the latest
        Windows 10 SDK (10.0.17763.0)

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code (version 1.44.1)
    • VS Code at C:\Users\<redacted>\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.9.1

[√] Connected device (2 available)
    • Mi A1   • 192.168.0.100:5555 • android-arm64 • Android 9 (API 28)
    • Windows • Windows            • windows-x64   • Microsoft Windows [Version 10.0.18363.778]
```

**Comment by devtronic** [comment]
Did you add the camera permissions to the manifest.xml?

**Comment by themisir** [comment]
Yes, here's `AndroidManifest.xml` file.

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="**REDACTED**">
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION" />
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
    <uses-feature android:name="android.hardware.camera" />
```

**Comment by themisir** [comment]
Hm, I think it's flutter related issue, https://github.com/flutter/flutter/issues/46952 same thing happened to other camera packages too.

**Comment by dingzuhua** [comment]
It seems like the old version was fine, but I had a problem upgrading it to 3.0.0

**Comment by dingzuhua** [comment]
Is there a solution

**Comment by marcos930807** [comment]
> It seems like the old version was fine, but I had a problem upgrading it to 3.0.0

Same problem for me and after capture a code dont return ScanResult

**Comment by aburcheri** [comment]
3.0.1 still throws this error

> E/libc    (27996): Access denied finding property "vendor.camera.hal1.packagelist"

**Comment by cristovamsegundo** [comment]
I have the same problem as well. Barcode scan 3.0.1 - Flutter v1.17.1 - Android 10.

E/libc    ( 2279): Access denied finding property "vendor.camera.hal1.packagelist"

**Comment by devtronic** [comment]
Does this guide solves the problem? https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by cristovamsegundo** [comment]
It does, @devtronic! Thank you very much!

P.S.: For others having the same issue, it might be easier to erase your Android/iOS folders and simply use `flutter create` to restore everything; provided you have some kind of source control to restore all relevant changes you previously made.

**Comment by brenoasm** [comment]
@devtronic I'm having this issue using a POCOPHONE F1 (Android). I've tried to do your guide from 

> Does this guide solves the problem? https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

and I was not successfully. If I understood correctly, my  MainActivity should look like this (correct me if I'm wrong):

```
package packge_name

import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {

}
```

**Comment by marcos930807** [comment]
@devtronic my flutter proyect is post 1.12 and i have this issue on OP7 device, however in a pixel 2 it doesn't happens. I will update with more details later. i downgrade to 2.0.2 it raise the warning. both Android 10.

In versions prior to 3.0, although the warning constantly comes out, the scan works, however, in versions after 3, when the scan returns, nothing happens, no errors nothing.

I DownGrade to version 2.0.2

**Comment by abhi7009** [comment]
Hii,

This code will help definitely:
if (ContextCompat.checkSelfPermission(this, Manifest.permission.CAMERA) != PackageManager.PERMISSION_GRANTED) { ActivityCompat.requestPermissions(this, new String[] {Manifest.permission.CAMERA}, 50); }

**Comment by madhu000-code** [comment]
I am.also getting the same error plz help me

**Comment by themisir** [comment]
> I am.also getting the same error plz help me

Upgrading flutter version helped me. (I just upgraded flutter sdk, created a new project and moved all source files to new project folder)

**Comment by madhu000-code** [comment]
Thank you so much

**Comment by bharathiselvan** [comment]
I am still facing the below issue. I m using Flutter 1.20.4.. Can someone help on this?..  
E/libc    ( 9114): Access denied finding property "vendor.camera.aux.packagelist"

**Comment by madhu000-code** [comment]
Use 0.1.3  and go to terminal and upgrade the flutter ask

**Comment by madhu000-code** [comment]
Flutter sdk

**Comment by bharathiselvan** [comment]
I have already upgraded to latest version of flutter 1.2.04 and created a new project, but still getting this error..

**Comment by themisir** [comment]
> I have already upgraded to latest version of flutter 1.2.04 and created a new project, but still getting this error..

I could only wish you a good luck.

**Comment by madhu000-code** [comment]
Add  the activity to manifest file
