### ISSUE TITLE
Save scanned QR to file \ image gallery

### ISSUE THREAD

**Issue by nirbar89** [mintware-de/flutter_barcode_reader#216]
Hi,

there is any way to save the scanned QR to an image file?

**Comment by nirbar89** [comment]
Hi, any comment? doable?

**Comment by devtronic** [comment]
Save the image itself is not possible. You can export the scanned contents as a qr code using this library: https://pub.dev/packages/qr_flutter

**Comment by nirbar89** [comment]
it's funny on native code you can do this as regular image capture right after you recognized the object which give you a pretty good result.

i am asking that again because this is a main feature that i need to my app.

**Comment by devtronic** [comment]
Isn't it better to generate a QR code of the scanned result instead of using the captured image?
If you need it, feel free to create a fork of this repo, implement the feature and create a PR.

**Comment by nirbar89** [comment]
for my use case not i really need the image, but thanks for the challenge ill try to build this feature and sure once ill done ill share this

**Comment by JoseGeorges8** [comment]
@nirbar89 Hi did you ever build this feature? I'm interested in it as well.

**Comment by nirbar89** [comment]
Hey, yes. I use firebase ML kit.
