### ISSUE TITLE
[Feature Request] Cancel scan programmatically

### ISSUE THREAD

**Issue by dd9k** [mintware-de/flutter_barcode_reader#220]
I want set timeout for BarcodeScanner and it auto closes without click button cancel. How can I do that? Thanks in advance. Happy coding.

**Comment by devtronic** [comment]
For this feature we need to implement a kind of cancellation token which is passed through the scan method to the platform specific code.
Or we add a "Cancel" method in the [platform_wrapper.dart](https://github.com/mintware-de/flutter_barcode_reader/blob/master/lib/platform_wrapper.dart) which cancels the scan on the platform side.

Feel free to create a PR ;-)
