### ISSUE TITLE
validateClientPermissionsLocked

### ISSUE THREAD

**Issue by zuwuko** [mintware-de/flutter_barcode_reader#224]
Example works when I run it, but if I copy the example code to a new flutter project I get this error. It never prompts for the permission to use camera. I already set the permission in android/app/src/main and android/app/src/debug and android/app/src/profile
`    <uses-permission android:name="android.permission.CAMERA" />`

Heres the error:
`W/CameraBase( 9110): An error occurred while connecting to camera 0: Status(-8, EX_SERVICE_SPECIFIC): '1: validateClientPermissionsLocked:978: Caller "com.example.bartest" (PID 10135, UID 9110) cannot open camera "0" without camera permission'`

**Comment by marcos930807** [comment]
After upgrading to v3.0.0 this error appears
W/CameraHandlerTh(31754): type=1400 audit(0.0:1265123): avc: denied { read } for name="u:object_r:persist_camera_prop:s0" dev="tmpfs" ino=26028 scontext=u:r:untrusted_app_27:s0:c198,c257,c512,c768 tcontext=u:object_r:persist_camera_prop:s0 tclass=file permissive=0

**Comment by devtronic** [comment]
I can't reproduce the issue, sorry. Please provide a minimal example how to reproduce the problem.
