### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kenneth1106** [mintware-de/flutter_barcode_reader#227]
Hi
I just integrate the v3.0.0 and try to use the scanner on Android.
I can grant the camera access right, and can launch the camera and scan the code by this command:
`var result = await BarcodeScanner.scan();`

But when the camera scanned the code and close the scanning screen, the code after can't be performed.
I can't print the result after scan, even the break point doesn't work.
The log after scan keep receive this:
`I/Timeline(10121): Timeline: Activity_idle id: android.os.BinderProxy@94d06 time:102536233`

But on iOS is working fine.
Am I missing something for the Android settings?
Hope someone could help me on this.
Thanks!

**Comment by devtronic** [comment]
Sounds like you're using the library with a project which was created with pre Flutter 1.12.
Instructions to fix the problem / update your project to Flutter 1.12: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
