### ISSUE TITLE
Incorrect argument when trying to run it on Xcode

### ISSUE THREAD

**Issue by heyabredda** [mintware-de/flutter_barcode_reader#23]
![screen shot 2018-06-15 at 22 26 02](https://user-images.githubusercontent.com/36278356/41490254-2403499e-70eb-11e8-96c0-98964ed8a915.png)

I am desperately trying to figure out what cause this issue as I have tried to do pretty much everything by following some others advice that have encountered the same issue, but apparently the issue persist..

**Comment by devtronic** [comment]
Is this still a problem?
