### ISSUE TITLE
[Bug]Access denied finding property "camera.aux.packagelist"

### ISSUE THREAD

**Issue by cmld** [mintware-de/flutter_barcode_reader#230]
**Describe the bug**
E/libc    ( 8313): Access denied finding property "camera.aux.packagelist"
E/libc    ( 8313): Access denied finding property "camera.aux.packagelist"
E/libc    ( 8313): Access denied finding property "camera.aux.packagelist"
E/libc    ( 8313): Access denied finding property "camera.aux.packagelist"
W/CameraHandlerTh( 8313): type=1400 audit(0.0:427215): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=22418 scontext=u:r:untrusted_app_27:s0:c58,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    ( 8313): Access denied finding property "camera.aux.packagelist"
W/CameraHandlerTh( 8313): type=1400 audit(0.0:427216): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=22418 scontext=u:r:untrusted_app_27:s0:c58,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0

Android can enter the shooting interface, but no results can be obtained in the code.
iOS is normal

**Comment by devtronic** [comment]
Dupe of #212
