### ISSUE TITLE
Return image object [Feature Request]

### ISSUE THREAD

**Issue by digibum** [mintware-de/flutter_barcode_reader#236]
There are use cases that require original image that was used to detect bar code, with witch you can prove read bar code. Etc: when security guard picks up bag with cash, bar code is scanned from bag. If for some reason bar code is read wrong or is corrupted, an original image should be available for later diagnostics...

Result should contain image object or path to image.

**Comment by devtronic** [comment]
Dupe of https://github.com/mintware-de/flutter_barcode_reader/issues/216
