### ISSUE TITLE
Ability to only allow certain barcode types to scan?

### ISSUE THREAD

**Issue by goodis0** [mintware-de/flutter_barcode_reader#24]
I have an issue where I am trying to scan a barcode which is directly underneath another barcode.  One is a simple 1-D barcode (not the one I want) and the other is a 2-D PDF417 barcode.

**Comment by matthewtsmith** [comment]
This library uses zbar which is a library for both iOS and Android. I believe Zbar lets you specify which barcode types you want to read. The plugin could be extended to include that functionality. PRs welcome!

**Comment by goodis0** [comment]
I'm not sure how to even begin that process!

**Comment by devtronic** [comment]
See #169
