### ISSUE TITLE
[Bug]Versions after 3.0.0 have no response after scanning Android code

### ISSUE THREAD

**Issue by cv0cv0** [mintware-de/flutter_barcode_reader#240]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, add the verbose output of `flutter run`.

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [ ] Android? Version: ...Android 9
 - [ ] Real Device? Which?: ...
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan`3.0.1
 - Output of `flutter --version`:
```
Flutter ...1.12.13+hotfix.9
```

**Additional context**
<img width="385" alt="图片" src="https://user-images.githubusercontent.com/18623780/81469164-1b1c5980-9216-11ea-9e46-d7f69b0616b9.png">
I ran the code in debug mode without taking the second line.

**Comment by devtronic** [comment]
Please follow this guide to solve the problem:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by joshuakoh1** [comment]
@devtronic The guide did not solve the problem
