### ISSUE TITLE
Unresolved reference: binaryMessenger

### ISSUE THREAD

**Issue by OmarACY** [mintware-de/flutter_barcode_reader#242]
**Describe the bug**
The application not compile
C:\Users\USERNAME\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\barcode_scan-3.0.1\android\src\main\kotlin\de\mintware\barcode_scan\BarcodeScanPlugin.kt: (22, 62): Unresolved reference: binaryMessenger

**To Reproduce**
1. Install barcode fllow steps for Android https://pub.dev/packages/barcode_scan#-readme-tab-
2. Run project
3. See error

**Expected behavior**
I hope it compiles

**Screenshots**
![image](https://user-images.githubusercontent.com/22042762/81620971-ccf08d00-93b2-11ea-8923-468ab6608566.png)

**Logs**
If applicable, add the verbose output of `flutter run`.

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [x] Android? Version: ...
 - [ ] Real Device? Which?: ...
 - [x] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan` : ^3.0.1
 - Output of `flutter --version`: 1.10.7

**Comment by devtronic** [comment]
Looks like your project was created using Flutter <1.12.
See this guide for migration: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
