### ISSUE TITLE
Nothing happens after the code is scanned

### ISSUE THREAD

**Issue by moacyrfc** [mintware-de/flutter_barcode_reader#243]
The execution of the program goes well until
barcode = await BarcodeScanner.scan(); , when the scanning window is opened and the barcode is read. After that, no further instructions are executed, nothing happens, no exceptions are thrown, the application does not crash and no response appears in the debug.

**Comment by devtronic** [comment]
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
