### ISSUE TITLE
[Feature Request] Some way to enter barcode manually when it's not scanned automatically

### ISSUE THREAD

**Issue by sviridov** [mintware-de/flutter_barcode_reader#245]
**Is your feature request related to a problem? Please describe.**
Some barcodes which I scan are quite poor quality and the scanner cannot identify them. I would like to give my users some way to enter barcode manually in such cases.

**Describe the solution you'd like**
I would like to have a text field where users could insert a barcode manually. Since I want to customize the appearance of such a text field I think that it makes sense to not open barcode scanner fullscreen but rather provide a barcode scanner widget that developers will be able to insert wherever they want.

**Additional context**
See below how it works in MyFitnessPal. It looks ugly but it gives you an idea of what I would like to achieve.

![image](https://user-images.githubusercontent.com/1789390/82595741-8de6e680-9bbf-11ea-93be-f13d3691643d.png)

**Comment by kikoba** [comment]
I added a textfield and a button in the start page

**Comment by sviridov** [comment]
Sorry, what start page you are talking about?

**Comment by devtronic** [comment]
Sorry but this feature request is too specific. Maybe it'll be possible on your own when this was solved: https://github.com/mintware-de/flutter_barcode_reader/issues/187

**Comment by sviridov** [comment]
If you mean that I will be able to insert the scanner inside a custom widget tree, then yes, that would definitely help.
