### ISSUE TITLE
[Bug] not getting any results with 3.00 and 3.0.1 

### ISSUE THREAD

**Issue by mohammedali933** [mintware-de/flutter_barcode_reader#249]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
the version 2.0.2 is currently working but when trying to update to 3.00 and 3.01 is not getting any results or errors! , the scanner camera is on and when scanning barcode no there are no results ,
i've followed the documentation and add all necessary  code lines

**To Reproduce**
1. Go to scanner and press scan button or whatever function that calls the _scanQR() function 
2. it opens the camera but no errors or result gotten

**Expected behavior**
it must return a result for the scanned barcode

**Screenshots**
Part of code:
![error-1](https://user-images.githubusercontent.com/27096774/83152241-4358f300-a106-11ea-9e0e-e32bcf0e15ad.png)
barcode scanned:
![image](https://user-images.githubusercontent.com/27096774/83152516-929f2380-a106-11ea-84fd-37ebc45d6c81.png)
Run Log:
![ERROR-2](https://user-images.githubusercontent.com/27096774/83152733-d09c4780-a106-11ea-951f-fbaf69fd0db2.png)

**Logs**
I/Timeline( 5462): Timeline: Activity_idle id: android.os.BinderProxy@2ee37988 time:116530035
I/Timeline( 5462): Timeline: Activity_launch_request id:com.smartersvision.food_delivery_app time:116535840
I/art     ( 5462): Background sticky concurrent mark sweep GC freed 14816(1074KB) AllocSpace objects, 14(224KB) LOS objects, 33% free, 2MB/4MB, paused 2.836ms total 391.259ms
I/Timeline( 5462): Timeline: Activity_idle id: android.os.BinderProxy@179a2a15 time:116536801
V/CameraPreview( 5462): Cancelling autofocus
I/art     ( 5462): Background partial concurrent mark sweep GC freed 3221(217KB) AllocSpace objects, 10(4MB) LOS objects, 41% free, 5MB/9MB, paused 7.085ms total 42.355ms
I/Timeline( 5462): Timeline: Activity_idle id: android.os.BinderProxy@2ee37988 time:116549373
I/art     ( 5462): Explicit concurrent mark sweep GC freed 2569(172KB) AllocSpace objects, 5(4MB) LOS objects, 57% free, 2MB/6MB, paused 735us total 59.992ms

**Environment (please complete the following information):**

 - [x] Android Version:  5.1.1
 - [x] Real Device: yes, Sony Xperia c3 lollipop 5.1.1
 - Version of `barcode_scan` : 3.00 , 3.0.1
 - Output of `flutter --version`:$ flutter --version
Flutter 1.17.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision f7a6a7906b (2 weeks ago) • 2020-05-12 18:39:00 -0700
Engine • revision 6bc433c6b6
Tools • Dart 2.8.2

**Additional context**
nothing

**Comment by devtronic** [comment]
This guide will solve the problem: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
