### ISSUE TITLE
Can i put it in a Widget that take the half of the screen ?

### ISSUE THREAD

**Issue by MaxmaxB** [mintware-de/flutter_barcode_reader#25]
Hi, 

I want to do something like that : 
<img width="360" alt="scan_barcode" src="https://user-images.githubusercontent.com/31889130/41767973-562509f6-760b-11e8-9754-f3f2eb1dc696.png">

Is it possible with this library?

**Comment by matthewtsmith** [comment]
No, that is not possible currently.
