### ISSUE TITLE
[Bug] `scan()` does not return a result (or null) nor throw an error.

### ISSUE THREAD

**Issue by jifalops** [mintware-de/flutter_barcode_reader#254]
**Describe the bug**
`BarcodeScanner.scan()` does not return a result, null, or throw an exception.
The scanner Activity runs and exits after scanning a barcode, but no errors are logged.

**To Reproduce**
- System is Ubuntu 18.04.
- I installed `protobuf` via `pip install protobuf`.
- Activated `pub global activate protoc_plugin`
- `proto3` VS code plugin is installed.
- Is there another step to setup the system?
```dart
        try {
          final result = await BarcodeScanner.scan().catchError((e) {
            log.e('Barcode scan threw exception.', e);
          });
          log.v('Scan result: $result');
        } catch (e) {
          log.e('Barcode scan threw exception.', e);
        }
```
**Expected behavior**
_Something_ should be logged. 

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [x] Android? Version: 29
 - [X] Real Device? Pixel 4
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan`: 3.0.1
 - Output of `flutter --version`:
```
Flutter 1.17.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision e6b34c2b5c (5 weeks ago) • 2020-05-02 11:39:18 -0700
Engine • revision 540786dd51
Tools • Dart 2.8.1
```

**Comment by nilsreichardt** [comment]
Same issue!

**Comment by devtronic** [comment]
Pick one of them... https://github.com/mintware-de/flutter_barcode_reader/issues?q=is%3Aissue+is%3Aclosed+no+result

Upgrade Guide:
https://github.com/mintware-de/flutter_barcode_reader/blob/master/UPGRADE.md#upgrade-from-2x-to-300
