### ISSUE TITLE
[Bug] Barcode detected as EAN13 not UPC

### ISSUE THREAD

**Issue by steve28100** [mintware-de/flutter_barcode_reader#255]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
Hello, I am trying this plugin to scan the barcode, it works fine in Android when using without options. The result is like this:
```
I/flutter ( 7122): Barcode
I/flutter ( 7122): 028190009849
I/flutter ( 7122): unknown
I/flutter ( 7122): UPC_A

```
However I need to restrict the barcode type so I give the options like this:

```
 var options = ScanOptions(restrictFormat: [
      BarcodeFormat.unknown,
      BarcodeFormat.ean13
    ]);
    var result = await BarcodeScanner.scan(options: options);

    print(result.type); // The result type (barcode, cancelled, failed)
    print(result.rawContent); // The barcode content
    print(result.format); // The barcode format (as enum)
    print(result
        .formatNote); // If a unknown format was scanned this field contains a note
```

However the result now is changed into EAN-13, it should be detected as UPC_A same like with no options.

```
flutter: Barcode
flutter: 0028190009849
flutter: ean13
flutter:
```
Also in IOS the barcode is always detected as EAN13 not UPC. 

**To Reproduce**
1. Add the options code in barcode scan
2. Scan the barcode image
3. Check the result

**Expected behavior**
It should be show as UPC_A Format

**Screenshots**
This is the image of barcode:
![WhatsApp Image 2020-05-19 at 3 29 20 PM (1)](https://user-images.githubusercontent.com/55441199/84229198-2ca59980-ab13-11ea-9cb4-bf2f11da16e6.jpeg)

**Logs**
Second Result after restricted:
```
flutter: Barcode
flutter: 0028190009849
flutter: ean13
flutter:
```

**Environment (please complete the following information):**
 - [X] iOS? Version: 12.4.6
 - [X] Android? Version: 9
 - [X] Real Device? Iphone 6, Asus Zenfone Max Pro M1
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan`: barcode_scan: ^3.0.1
 - Output of `flutter --version`:
```
Flutter 1.17.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 5f21edf8b6 (12 days ago) • 2020-05-28 12:44:12 -0700
Engine • revision b851c71829
Tools • Dart 2.8.3
```

**Additional context**
This is the result using online site barcode reader,it shows correct value and format:
<img width="1397" alt="barcode_result" src="https://user-images.githubusercontent.com/55441199/84235273-c7a47080-ab1f-11ea-92fd-ee868fd853ef.png">

**Comment by devtronic** [comment]
EAN13 is compatible to UPC. On iOS the default AVFoundation barcode detection is used. I think we don't have a chance to fix this "problem". You can restrict the barcode formats in the scan options and exclude ean13 if you need to scan this type of codes as UPC.

**Comment by samo92** [comment]
If i exclude ean13 the app dont scan anything.
