### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by qiqetes** [mintware-de/flutter_barcode_reader#256]
**BUG REPORTS WITHOUT PROVIDING THESE INFORMATIONS WILL BE CLOSED DIRECTLY. DON'T REMOVE THE SECTIONS!**

**Describe the bug**
scan() doesn't end in 3.0.1 but it does in other versions

**To Reproduce**
```
Future scanQR() async {
    try{
      // run
      var codeScanner = await BarcodeScanner.scan();
      // doesn't run 
      print(codeScanner.rawContent);
      _showDialog(context, codeScanner.rawContent);
    }catch(e){
      // doesn't run
      print(e);
    }
  }
```

**Expected behavior**
It should print or do the stuff after the scan()

**Screenshots**

**Logs**
If applicable, add the verbose output of `flutter run`.

**Environment (please complete the following information):**
 - [ ] iOS? Version: ...
 - [ x] Android? Version: Android Q
 - [ x] Real Device? Which?: Motorola One
 - [ ] Emulator/Simulator? Which?: ...
 - Version of `barcode_scan` 3.0.1
 - Output of `flutter --version`: latest
```
Flutter ...
```

**Additional context**

**Comment by sergioramoshc** [comment]
+1

Which version have you tested and worked?

**Comment by qiqetes** [comment]
> +1
> 
> Which version have you tested and worked?
I'm currently using 2.0.0, and it works as intended

**Comment by qiqetes** [comment]
> +1
> 
> Which version have you tested and worked?

I'm currently using 2.0.0, and it works as intended

**Comment by devtronic** [comment]
https://github.com/mintware-de/flutter_barcode_reader/blob/master/UPGRADE.md#upgrade-from-2x-to-300
