### ISSUE TITLE
have you declared this activity in your AndroidManifest.xml?

### ISSUE THREAD

**Issue by 12221010ll** [mintware-de/flutter_barcode_reader#26]
when i click "scan" the app has crashed.
 
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.met.metchain2/com.apptreesoftware.barcodescan.BarcodeScannerActivity}; have you declared this activity in your AndroidManifest.xml?

what that mean？

**Comment by hetkpatel** [comment]
I don't seem to know why, but I'm having this same issue. Did you by any chance figure out the solution?

**Comment by cbyniiaii** [comment]
flutter build apk 
adb install build/app/outputs/apk/release/app-release.apk
It's work! But Hot load?

**Comment by singi2016cn** [comment]
when I click the scan,I have same problem.what can I do?

```
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.hjly168.hjly/com.apptreesoftware.barcodescan.BarcodeScannerActivity}; have you decla
red this activity in your AndroidManifest.xml?
```

**Comment by j1dopeman** [comment]
I had this same error. I think the manifest changes don't get picked up. I deleted the build folder and then ran it again and it started working.

**Comment by hugohfs** [comment]
Deleting build folder works for me.

**Comment by chunhunghan** [comment]
Delete build folder works. Thank you all

**Comment by kshivam1177** [comment]
Deleted .gradle folder and then ran it again and it started working.
flutter_app/android/.gradle

**Comment by chaochaox1990** [comment]
it work for me thanks

**Comment by Loopex2019** [comment]
Thanks it worked for me

**Comment by Ray-56** [comment]
Thanks it worked for me

**Comment by lucascarvalho100** [comment]
it work for me thanks

**Comment by tyh520life** [comment]
> when I click the scan,I have same problem.what can I do?
> 
> ```
> android.content.ActivityNotFoundException: Unable to find explicit activity class {com.hjly168.hjly/com.apptreesoftware.barcodescan.BarcodeScannerActivity}; have you decla
> red this activity in your AndroidManifest.xml?
> ```

open in android studio , build project

**Comment by halladaas** [comment]
the app crashed before it even opened when i deleted the build.gradle file. is that what i was supposed to delete?
