### ISSUE TITLE
The title in the app bar should be controlled by the strings option.

### ISSUE THREAD

**Issue by fideldonson** [mintware-de/flutter_barcode_reader#265]
Using the project-name as the app bar title on the scanner window is limiting. Would really like the option to customize it.

Thanks for a great plugin - had it up and working in no time.

**Comment by devtronic** [comment]
Feel free to create a PR.
I'm closing this issue and reference it in https://github.com/mintware-de/flutter_barcode_reader/issues/265

**Comment by alexrosabr** [comment]
> Feel free to create a PR.
> I'm closing this issue and reference it in #265

You mean #187, right?

**Comment by Sandro-darli** [comment]
Hello! We already have a solution to change hide the title?
