### ISSUE TITLE
[Bug] example doesn't work

### ISSUE THREAD

**Issue by Alexufo** [mintware-de/flutter_barcode_reader#268]
latest flutter/ windows/

![2020-07-14_03-39-17](https://user-images.githubusercontent.com/1562329/87367500-d9948b80-c583-11ea-80b7-ed8c0275f346.jpg)

**Comment by LukasWestholt** [comment]
Why is the input line underlined?
Did you "Pub get"?

**Comment by Alexufo** [comment]
Yes.
1. F1. flutter: new project
2. Set dependences barcode_scan: any. 
3. flutter pub get
4. lib/main.dart replace all code from example

**Comment by Alexufo** [comment]
I cleared flutter\.pub-cache\hosted\pub.dartlang.org\barcode_scan-3.0.1
It works now
