### ISSUE TITLE
Clarity on error responses

### ISSUE THREAD

**Issue by treeder** [mintware-de/flutter_barcode_reader#269]
I see in the docs the following:

```dart
print(result.type); // The result type (barcode, cancelled, failed)
```

Are there cases where it would fail and not throw an exception?  Like we'd want to check for `result.type == failed` rather than catching an exception?

**Comment by devtronic** [comment]
There is no ResultType.Failed. ResultType.Error comes from here: 
- https://github.com/mintware-de/flutter_barcode_reader/search?l=Kotlin&q=ResultType.Error 
- https://github.com/mintware-de/flutter_barcode_reader/search?l=Swift&q=%22type+%3D+.error%22

**Comment by treeder** [comment]
Ok, then the main README should change, it has "failed" in it.
