### ISSUE TITLE
[Bug] Camera Permission

### ISSUE THREAD

**Issue by pdefuns** [mintware-de/flutter_barcode_reader#274]
On iOS when the camera permissions are denied, it's only flickering

Can you please add a check before the camera is called to avoid flickering and display the user that the permission is needed with a link to the settings? Thx!

**Comment by devtronic** [comment]
That's something you should add in your client code. Check for the error code: https://github.com/mintware-de/flutter_barcode_reader/blob/bf7a8e04cbcb00ca6d07db3e2275f842c26622a7/lib/platform_wrapper.dart#L44-L52

**Comment by pdefuns** [comment]
I‘m checking it. But the flickering is happening anyway. So it should not flicker, if access not granted
