### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by Jojoooo1** [mintware-de/flutter_barcode_reader#277]
**Is your feature request related to a problem? Please describe.**
Would it be possible to have an option to embed the barcode reader in a container with a specific height instead of the whole screen ?

**Comment by Yaffar** [comment]
I'm also very interested in this implementation

**Comment by devtronic** [comment]
See also https://github.com/mintware-de/flutter_barcode_reader/issues/187
Feel free to create a pull request.
