### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by akreienbring** [mintware-de/flutter_barcode_reader#282]
**Is your feature request related to a problem? Please describe.**
No
**Describe the solution you'd like**
Can the title in the scan window be changed like the Flash On, Cancel .. text? It currently aperently shows the Name of my flutter project.... 

**Describe alternatives you've considered**
Sorry if I overlook another setting somewhere in my project that is used to set this title. Which one is it?

**Additional context**
None...

**Comment by devtronic** [comment]
At the moment this is only possible by setting the title in the Android Manifest. 
Example: https://github.com/mintware-de/flutter_barcode_reader/pull/280/files#diff-04c6e90faac2675aa89e2176d2eec7d8
