### ISSUE TITLE
Scan images from device

### ISSUE THREAD

**Issue by modulovalue** [mintware-de/flutter_barcode_reader#29]
I think it is an important feature to be able to scan QR codes not only from the camera but also from an image that was previously taken or downloaded from the web.

### Use case:
- Cryptocurrency addresses are often presented in the form of QR codes. 
Addresses are cryptic and not user-friendly therefore it is much more practical to share QR codes than the addresses themselves.

### Two features would be needed:

1. an image picker like [this library](https://pub.dartlang.org/packages/image_picker/)
2. Libraries to scan the images

### Solution
One approach is to additionally use other libraries for iOS/Android that support this feature.
e.g. [iOS](https://github.com/EyreFree/EFQRCode) and [Android](https://stackoverflow.com/a/14938165/9545358)

The other way would be to kindly ask [here](https://github.com/mikebuss/MTBBarcodeScanner/) and [here](https://github.com/dm77/barcodescanner/) if they could implement this feature. It doesn't seem to be a big deal but I might be overlooking something.

What do the maintainers of this library think of that?

**Comment by matthewtsmith** [comment]
I think this falls outside the scope of this library. I would recommend making a separate plugin that uses the build in libraries in iOS and Android instead.
