### ISSUE TITLE
Make iOS scanner view appear as Android does

### ISSUE THREAD

**Issue by dustin-graham** [mintware-de/flutter_barcode_reader#35]
With a scan window and a scan line. barcodes should only scan if they intersect with the scan line.

**Comment by dustin-graham** [comment]
PR: https://github.com/apptreesoftware/flutter_barcode_reader/pull/34

@matthewtsmith ^

**Comment by matthewtsmith** [comment]
@dustin-graham I had to remove the scanLine change you added in #34 . 

https://github.com/apptreesoftware/flutter_barcode_reader/pull/42

It was causing QR codes not to read.

**Comment by dustin-graham** [comment]
@matthewtsmith I'll look back at it again to see if I can make it work. In my case I really need the scan line for precision in my app's scenarios.
