### ISSUE TITLE
Plz update SDK constraint to support Dart 2.1.0

### ISSUE THREAD

**Issue by hnvn** [mintware-de/flutter_barcode_reader#36]
I've just upgraded my project to Flutter v0.5.9. My project can't compile by the error: 
```
The current Dart SDK version is 2.1.0-dev.0.0.flutter-be6309690f.

Because bibomart depends on barcode_scan >=0.0.2 which requires SDK version <2.0.0, version solving failed.                                                               
pub get failed (1)

```
Please, update the SDK constraint of your library to support the latest version of flutter sdk. Thanks in advance.

**Comment by natebgurutech** [comment]
I would really like this updated as well!
