### ISSUE TITLE
iOS engine failure

### ISSUE THREAD

**Issue by victoraugustolls** [mintware-de/flutter_barcode_reader#40]
Hi!

With the new version `0.0.6` I started having some problems only on iOS.

The first scan works fine, but when I press cancel or scan a QR Code, I receive the following messages:

```
[VERBOSE-2:engine.cc(158)] Could not prepare to run the isolate.
[VERBOSE-2:engine.cc(117)] Engine not prepare and launch isolate.
[VERBOSE-2:FlutterViewController.mm(411)] Could not launch engine with configuration.
```

Also, if I click on the camera screen, I can interact with the flutter app underneath, but only on iOS too.

Other issue is that on iOS most of the time is not even scanning anymore, I have to open and close the screen multiple times.

**Comment by victoraugustolls** [comment]
Update:

- version `0.0.6` is not scanning at all

- version `0.0.5` is working fine, but throwing those logs above, so it must be a flutter issue not plugin

**Comment by matthewtsmith** [comment]
I can't explain the engine.cc outputs but I did find the issue where QR codes won't scan.
 Fixing in https://github.com/apptreesoftware/flutter_barcode_reader/pull/42

**Comment by victoraugustolls** [comment]
@matthewtsmith thanks! Will test ASAP
