### ISSUE TITLE
Ability to highlight the barcode in live view and allow user to tap on desired barcode

### ISSUE THREAD

**Issue by manikvashisht** [mintware-de/flutter_barcode_reader#43]
The ability for the user to scan the barcode is awesome , but if this library can highlight the barcodes it is able to read in camera mode, plus user can tap on to select the desired barcode.

So essentially 2 feature request : 

1. Ability to highlight barcode in camera view
2. Ability to select highlighted barcode in a situation if user is scanning multiple barcodes at once.

Example App and Library would be : https://pub.dartlang.org/packages/flutter_mobile_vision

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
