### ISSUE TITLE
Because flutter_osc depends on barcode_scan ^0.0.7 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by BeyChan** [mintware-de/flutter_barcode_reader#45]
/Users/chengmingyong/flutter/bin/flutter --no-color packages get
Running "flutter packages get" in FlutterOSC...
Because flutter_osc depends on barcode_scan ^0.0.7 which doesn't match any versions, version solving failed.
pub get failed (1)

**Comment by devtronic** [comment]
Use the latest version 🙂
