### ISSUE TITLE
Rotating orientation on iPhones only shows half the screen

### ISSUE THREAD

**Issue by firsthour** [mintware-de/flutter_barcode_reader#61]
barcode_scan version 0.0.8
IOS version 11.4.1

Tested on iPhone 6 and iPhone 7.

https://i.imgur.com/3umeOrq.jpg

Start in portrait mode and then rotate the phone, it will switch to landscape mode but only the left side of the screen will show the camera.

Start in landscape mode and then rotate the phone, it will switch to portrait mode but only the top half of the screen will show the camera.

Semi-related to #56 in that I would like to disable landscape mode completely but an unsure how to do that on iPhones.

Thanks.

![landscape](https://user-images.githubusercontent.com/12001281/48802715-a679f600-ecd5-11e8-9b8c-e5e60f899677.jpg)

**Comment by jakolion** [comment]
> Semi-related to #56 in that I would like to disable landscape mode completely but an unsure how to do that on iPhones.

You set this in the Info.plist with the key "UISupportedInterfaceOrientations". Using Xcode you can find the setting in the "Deployment Info".

![image](https://user-images.githubusercontent.com/31564175/48892596-b95c0a00-ee3e-11e8-89bf-eb13a1efdf82.png)

The camera is not rotating then so this can be used as a workaround if landscape mode isn't a requirement for the app.

**Comment by rjahn** [comment]
I have the same problem but my app requires landscape mode, to show more information (sometimes).

**Comment by Mythar** [comment]
Still no fix using barcode_scan version 1.0.0

**Comment by SaltumDis** [comment]
Still having this issue 😢

**Comment by mertcanbs** [comment]
This issue is still present where locking device orientation is not possible.

**Comment by devtronic** [comment]
Solved in #167

**Comment by devtronic** [comment]
Will be available in the next release
