### ISSUE TITLE
PlatformException(PERMISSION_NOT_GRANTED, null, null)

### ISSUE THREAD

**Issue by lijunen2009** [mintware-de/flutter_barcode_reader#63]
my code
try {
      String barcode = await BarcodeScanner.scan();

      return {
        'status':200,
        'msg':'扫码成功',
        'result':barcode
      };
    } on PlatformException catch (e) {
      print(e);
      if (e.code == BarcodeScanner.CameraAccessDenied) {
        return {
          'status':200,
          'msg':'没有相机权限',
          'result':''
        };

      } else {
        return {
          'status':200,
          'msg':'未知错误:${e.toString()}',
          'result':''
        };

      }
    } on FormatException{
      return {
        'status':200,
        'msg':'用户取消',
        'result':''
      };
    } catch (e) {
      return {
        'status':200,
        'msg':'未知错误:${e.toString()}',
        'result':''
      };
    }
  }

Runner/info.plist
<key>NSCameraUsageDescription</key>
    <string>App需要您的同意,才能访问相机</string>

call get error flutter: PlatformException(PERMISSION_NOT_GRANTED, null, null)

**Comment by alsocalledchris** [comment]
I also get this error, even if I use a different plugin to grant permission first - this does not see granted permission and errors with the PlatformException(PERMISSION_NOT_GRANTED, null, null)

**Comment by hoangcao10** [comment]
same error

**Comment by jeidison** [comment]
https://stackoverflow.com/questions/25486080/how-to-access-ios-simulator-camera

**Comment by karedem** [comment]
i meet the same bug, hope to fix

**Comment by karedem** [comment]
base on MTBBarcodeScanner , hope return more infomation when grant permission failed,

**Comment by devtronic** [comment]
Unfortunately, the iOS simulator does not support camera features.
