### ISSUE TITLE
The transition is not smooth

### ISSUE THREAD

**Issue by Peras795** [mintware-de/flutter_barcode_reader#69]
Hello,

First of all thank you for creating the library that allows us add the barcode scanner on our apps.
Although the library works perfect, I've noticed a little bit of lagging in the transition the current flutter screen and the barcode scanner.

Is this a bug? Can I override the animation to make the transition smoother?

Thank you in advanced,

Alex.

**Comment by NatoBoram** [comment]
This is what I get : 

```log
I/Choreographer(14295): Skipped 61 frames!  The application may be doing too much work on its main thread.
```

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
