### ISSUE TITLE
Having issue trying the example

### ISSUE THREAD

**Issue by gernest** [mintware-de/flutter_barcode_reader#7]
Hi, I'm new to dart/flutter/mobile. I followed the example but I'm getting  UnknownError : MissingPluginException ( No implementation found for method scan on channel com.appfreesofware.barcode_scan) when I click the scan button

I'm using the Simulator to test 

```
$ flutter --version
Flutter 0.1.4 • channel beta • https://github.com/flutter/flutter.git
Framework • revision f914e701c5 (9 days ago) • 2018-02-19 21:12:17 +0000
Engine • revision 13cf22c284
Tools • Dart 2.0.0-dev.27.0-flutter-0d5cf900b0
```

Thanks in advance. I might be missing something so any pointers will be highly appreciated.

**Comment by matthewtsmith** [comment]
I'm wondering if this is having to do with the latest Flutter SDK updates. I will try to take a look and see if I have issues running the example on the latest SDK.

**Comment by gernest** [comment]
Apologies, It was my mistake. I was using the emulator, I tried the example with real device and it is working fine.

**Comment by RAFI-006** [comment]
I am testing with real device error is same,any suggestion will be highly appreciated

**Comment by liupan163** [comment]
> I am testing with real device error is same,any suggestion will be highly appreciated

i have same problem

**Comment by myfbone** [comment]
huh.
any solutions? :)
