### ISSUE TITLE
Scanning outside the "window" on iOS

### ISSUE THREAD

**Issue by magnus-lpa** [mintware-de/flutter_barcode_reader#77]
I noticed that on an iPad with iOS 12.1, barcodes are scanned even when they are in the dimmed area outside the scanning rectangle. 

Doesn't really affect performance other than being confusing when trying to read QR-codes that are placed near each other (I noticed it when testing with some QR-codes printed on a paper, and thought I was scanning a particular QR-code while in reality I was scanning the one next to it which was in the dimmed area).

**Comment by devtronic** [comment]
Closed. Feel free to join the discussion in the tracker issue [#187 UI customization](187)
