### ISSUE TITLE
Android emulator "virtual scene" not triggering QR-reader

### ISSUE THREAD

**Issue by magnus-lpa** [mintware-de/flutter_barcode_reader#80]
The Android emulator has a nice feature called "virtual scene", in which you can test apps that use the camera in a 3D environment and with the possibility to display images such as QR-codes.

Unfortunately, the QR-code scanner is not trigger by such images in the emulator, which makes development less convenient (basically having to bypass the QR code scanner unless testing on a real device). It would be a great feature to be able to trigger the QR-code reader in the emulator.

**Comment by devtronic** [comment]
I can not reproduce the issue. In the latest version the QR code is recognized in the virtual scene.
[Screenshot_1582405282](https://user-images.githubusercontent.com/2362734/75099177-ec9bc480-55be-11ea-95e8-ba144695ba76.png)
