### ISSUE TITLE
Embed on widget

### ISSUE THREAD

**Issue by pmcarlos** [mintware-de/flutter_barcode_reader#81]
Is there any way to embed the scanner on a widget, lets say I need my scaffold with appBar and a bottom Text which gives me in realtime the qr scanned, and keep the camera always scanning?
At the moment how it works it opens a new Widget or kind of with full screen camera and 2 top buttons (Cancel and Flash)

**Comment by matthewtsmith** [comment]
This can't be done with this library. It would have to take advantage of the new `native view` feature of Flutter. PRs welcome for this.
