### ISSUE TITLE
Cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX

### ISSUE THREAD

**Issue by Laysros** [mintware-de/flutter_barcode_reader#83]
I can not use these both flutter plugins together:

  cloud_firestore: ^0.9.0+2
  barcode_scan: ^0.0.8
When run, error occured:

D8: Program type already present: android.arch.core.util.Function
     *********************************************************
WARNING: This version of cloud_firestore will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https: //goo.gl /CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.
it compiled and runned on Android phone when I remove one of them. But both can not go together. How to fix?

**Comment by renannprado** [comment]
@Laysros does it help?
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility#avoiding-androidx
**maybe** if you use `cloud_firestore: 0.8.2+3` you wouldn't have this error

**Comment by matthewtsmith** [comment]
Published 1.0 to pub with this fix
