### ISSUE TITLE
Unable to run app. Gradle build failing continuously for Android

### ISSUE THREAD

**Issue by AmolGangadhare** [mintware-de/flutter_barcode_reader#86]
**Issue**
Unable to run app as gradle build is failing.

**Steps to reproduce :**
1. Steps give on https://github.com/apptreesoftware/flutter_barcode_reader

**Log**
* Error running Gradle:
ProcessException: Process "/Users/admin/Desktop/TestApp/flutter_app/android/gradlew" exited abnormally:

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':barcode_scan'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
  Command: /Users/admin/Desktop/TestApp/flutter_app/android/gradlew app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by fritz-playmaker** [comment]
Check these steps. It worked for me 

https://github.com/apptreesoftware/flutter_barcode_reader/issues/71#issuecomment-468291746

**Comment by moseskarunia** [comment]
Check whether you already enabled kotlin or not.
