### ISSUE TITLE
Barcode reader must have a  kotlin-stdlib-jre7:?

### ISSUE THREAD

**Issue by yenoss** [mintware-de/flutter_barcode_reader#87]
## Environment
*  Android studio 3.3.1
*  com.android.tools.build:gradle:3.0.1
*  org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21
*  implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:1.3.21"
* kotlin plugin version : 1.3.21-release-Studio3.3-1
*  barcode_scan: "^0.0.3"

## Problem
I show errors when I click running button.

And I shown this comment

> kotlin-stdlib-jre7 is deprecated since 1.2.0 and should be replaced with kotlin-stdlib-jdk7 less... (⌘F1) 
> Inspection info: This inspection reports that some deprecated dependency is used in Gradle.

So I guess barcode reader need to  kotlin-stdlib-jre7. 

Then Am I DownGrade some gradle settings? (it mean, project will be set up kotlin-stdlib-jre7 envorinment)

## Failure Infomation
`Gradle task 'assembleDebug'...

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> Could not find org.jetbrains.kotlin:kotlin-stdlib-jre7:1.3.21.
  Searched in the following locations:
    - file:/Users/yenos/Library/Android/sdk/extras/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - file:/Users/yenos/Library/Android/sdk/extras/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - file:/Users/yenos/Library/Android/sdk/extras/google/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - file:/Users/yenos/Library/Android/sdk/extras/google/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - file:/Users/yenos/Library/Android/sdk/extras/android/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - file:/Users/yenos/Library/Android/sdk/extras/android/m2repository/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
    - https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.pom
    - https://maven.google.com/org/jetbrains/kotlin/kotlin-stdlib-jre7/1.3.21/kotlin-stdlib-jre7-1.3.21.jar
  Required by:
      project :app > project :barcode_scan

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
Finished with error: Gradle task assembleDebug failed with exit code 1`

plz, give me a some advice. 

thanks

**Comment by matthewtsmith** [comment]
Published 1.0 to pub with this fix
