### ISSUE TITLE
now kotlin version is 1.2.51 but androidx need 1.3.0

### ISSUE THREAD

**Issue by blueisboy** [mintware-de/flutter_barcode_reader#89]
the error in my new computer.  what can I do? only change something versions.

* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.0 and higher.
The following dependencies do not satisfy the required version:
project ':barcode_scan' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.51

**Comment by techgents** [comment]
Our dev team is having the same issue. It seems the Android X roll out/update has forced the use of Kotlin Gradle 1.3.0 and as a result we cannot use the scanner.

**Comment by fritz-playmaker** [comment]
similar issue here

**Comment by fritz-playmaker** [comment]
Check these steps. It worked for me 

https://github.com/apptreesoftware/flutter_barcode_reader/issues/71#issuecomment-468291746

**Comment by matthewtsmith** [comment]
Published 1.0 to pub with this fix
