### ISSUE TITLE
Localize the Flash On/Off button would be better

### ISSUE THREAD

**Issue by learning** [mintware-de/flutter_barcode_reader#91]
The **Flash On/Off** button text is hard coded now, localize it would be better.

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5d498e39a76466b03579486475ec777fba33ed2c/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt#L39

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5d498e39a76466b03579486475ec777fba33ed2c/android/src/main/kotlin/com/apptreesoftware/barcodescan/BarcodeScannerActivity.kt#L43

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5e360fc9dad8f3525e75aaaf6e7d64490759eda2/ios/Classes/BarcodeScannerViewController.m#L93

https://github.com/apptreesoftware/flutter_barcode_reader/blob/5e360fc9dad8f3525e75aaaf6e7d64490759eda2/ios/Classes/BarcodeScannerViewController.m#L97

**Comment by angel1st** [comment]
+1 on the above. I would even suggest an easier IMO approach - rather than localize the button, it can be replaced with icon pair Flash on / off.

**Comment by gabrieleleo** [comment]
would be really awesome!!

**Comment by linguitang** [comment]
+1

**Comment by hehuapei** [comment]
+1

**Comment by josephyuen** [comment]
+1

**Comment by hanlike** [comment]
+1

**Comment by masewo** [comment]
> +1 on the above. I would even suggest an easier IMO approach - rather than localize the button, it can be replaced with icon pair Flash on / off.

I replaced flash toggle title by two icons in my fork.

**Comment by devtronic** [comment]
As mentioned here https://github.com/mintware-de/flutter_barcode_reader/issues/131#issuecomment-588521486 I need to rewrite the platform communication. After that it's possible to use custom strings.

**Comment by devtronic** [comment]
Soon :-) 
![image](https://user-images.githubusercontent.com/2362734/75091685-7c665200-5570-11ea-88c5-219f1ecb06bb.png)

**Comment by devtronic** [comment]
Feel free to test: https://github.com/mintware-de/flutter_barcode_reader/pull/185

**Comment by devtronic** [comment]
https://pub.dev/packages/barcode_scan/versions/3.0.0-dev.1
