### ISSUE TITLE
Error in version 1.0.0

### ISSUE THREAD

**Issue by dxdiagmauric** [mintware-de/flutter_barcode_reader#93]
Error build app: barcode_scan: ^1.0.0

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':barcode_scan'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

This problem disapear in version 0.0.8

**Comment by albo1337** [comment]
same here!

**Comment by albo1337** [comment]
Fixed it! You have to uprade your build.gradle (project level) to kotlin version 1.3.20 and gradle 3.3.1. Then it should work with version 1.0.0 and AndroidX support.

**Comment by matthewtsmith** [comment]
@albo1337 solution is correct. You must updated gradle to AndroidX. If you are not ready to update yet, then stay on 0.0.8
