### ISSUE TITLE
com.apptreesoftware.barcodescan.BarcodeScannerActivity

### ISSUE THREAD

**Issue by blackmakerblm** [mintware-de/flutter_barcode_reader#97]
my xml file can't resolve the following <activity android:name="com.apptreesoftware.barcodescan.BarcodeScannerActivity"/>
and when i ignore the error and hot reload my flutter app when i click on scan i have the following exception not found method ...on chanel com.apptreesoftware.barcode_scan

**Comment by OsmiPotnik** [comment]
Are you using Visual Studio Code? Assuming you have the same issue I have, I fixed it by going into the project folder and deleting the **build** folder and then rebuilt my app again. This fixed the error and the camera opened. I suspect rebuilding the project should work in other IDEs aswell.

**Comment by hehuapei** [comment]
> Are you using Visual Studio Code? Assuming you have the same issue I have, I fixed it by going into the project folder and deleting the **build** folder and then rebuilt my app again. This fixed the error and the camera opened. I suspect rebuilding the project should work in other IDEs aswell.

It works! thanks!

**Comment by miguelgalindez** [comment]
it also worked for me! Thank you very much!

**Comment by UtkarshChandel** [comment]
> Are you using Visual Studio Code? Assuming you have the same issue I have, I fixed it by going into the project folder and deleting the **build** folder and then rebuilt my app again. This fixed the error and the camera opened. I suspect rebuilding the project should work in other IDEs aswell.

Thanks @OsmiPotnik was stuck on this for hours.

**Comment by UtkarshChandel** [comment]
this Closes #97
