### ISSUE TITLE
Switching page after a qr scan and crash

### ISSUE THREAD

**Issue by lunwhl** [mintware-de/flutter_barcode_reader#98]
Hi, I have deployed my flutter app with this package. Everything is good until I wanted to navigate my current page to the next page after scan.

The app is crashed after the scan or sometime it can navigate to the next page but it crashed when I switch page and scan again.

I navigate to another page in the scan() function.

Anyone know how to solve this issue?

**Comment by devtronic** [comment]
Please provide more details:
- Platform / version
- Error log / Stack / Minimal example to reproduce
