### ISSUE TITLE
iPhone 6 always crash when the app is in first run

### ISSUE THREAD

**Issue by lunwhl** [mintware-de/flutter_barcode_reader#99]
The app will crash for the first run after I open the barcode scan.

After the first crash then everything will be alright.

Is there any idea?

**Comment by DzSolution** [comment]
you same with me, please support us!

Xcode's output:
↳
    In file included from /Users/k/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.0/ios/Classes/FlutterStatusbarcolorPlugin.m:1:
    /Users/k/.pub-cache/hosted/pub.dartlang.org/flutter_statusbarcolor-0.2.0/ios/Classes/FlutterStatusbarcolorPlugin.h:1:9: fatal error: 'Flutter/Flutter.h' file not found
    #import <Flutter/Flutter.h>
            ^~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by matthewtsmith** [comment]
@lunwhl Can you provide the details of the crash?

**Comment by davidhsu1115** [comment]
Having same problem here, the crash rarely show up. But some time the app will crash and return to ios home page when scanning the barcode.

**Comment by bradintheusa** [comment]
Hi

I submitted my app to app store and the IOS reviewer says the same thing.  I'm posting the log here hoping it helps someone else more than it helped me.

[attachment-18120773179818384237crashlog-B9F3105E-5E42-41CE-88C3-13062C29028B (1).txt](https://github.com/apptreesoftware/flutter_barcode_reader/files/3612847/attachment-18120773179818384237crashlog-B9F3105E-5E42-41CE-88C3-13062C29028B.1.txt)
[attachment-18120773179818384237crashlog-B9F3105E-5E42-41CE-88C3-13062C29028B.txt](https://github.com/apptreesoftware/flutter_barcode_reader/files/3612848/attachment-18120773179818384237crashlog-B9F3105E-5E42-41CE-88C3-13062C29028B.txt)
[attachment-15741213354276122664crashlog-18EE94ED-6586-49B2-9A5E-27A76E2459A4.txt](https://github.com/apptreesoftware/flutter_barcode_reader/files/3612849/attachment-15741213354276122664crashlog-18EE94ED-6586-49B2-9A5E-27A76E2459A4.txt)


> Your app still crashed on iPad running iOS 12.4 on WiFi when we:
> 
> 1. Launched the app
> 2. Tapped + icon at the bottom right
> 3. Scanned QR code
> 4. App crashed

**Comment by devtronic** [comment]
Please update to the latest version and try it again
